# Neptunized theme

foreground             #768887
background             #FDF6E4
selection_foreground   #FDF6E4
selection_background   #768887

cursor                 #002D39
cursor_text_color      #FDF6E4

# (near-invisible)
color0                 #EAE7D7
color8                 #94A09C
# (red)
color1                 #D05A2E
color9                 #A24019
# (green)
color2                 #7A8E24
color10                #5C6C14
# (yellow)
color3                 #B58629
color11                #8D671D
# (blue)
color4                 #3587D3
color12                #2266A4
# (magenta)
color5                 #C967AC
color13                #9F4D86
# (cyan)
color6                 #24A592
color14                #1D8071
# (contrasty)
color7                 #345158
color15                #002D39

# Tabs
active_tab_foreground   #002D39
active_tab_background   #FFFFFF
inactive_tab_foreground #768887
inactive_tab_background #EAE7D7

# Windows
active_border_color     #AB8704
inactive_border_color   #EEDDAA
