# A test for now...

#  #FFE #fff8e6 #D23  #B52 #b6522d #C54 #cc5e35
#  #EED #eeeedf #A80  #A80 #ab8705 #C90 #bd9605
#  #998 #99998b #480  #783 #778a2d #893 #859a33
#  #776 #757568 #099  #198 #1ea28f #1A9 #1eb39e
#  #554 #545347 #07D  #37B #3578b8 #38C #3e87ce
#  #332 #313125 #C49  #A69 #b25e99 #B7A #c66aaa
#  #221 #17170c #D23  #B52 #b6522d #C54 #cc5e35


foreground             #545347
background             #fff8e6
selection_foreground   #fff8e6
selection_background   #545347

cursor                 #332
cursor_text_color      #ffffef

# (near-invisible)
color0                 #EED
color8                 #998
# (red)
color1                 #B52
color9                 #C54
# (green)
color2                 #783
color10                #893
# (yellow)
color3                 #A80
color11                #B91
# (blue)
color4                 #37B
color12                #38C
# (magenta)
color5                 #A69
color13                #B7A
# (cyan)
color6                 #1A9
color14                #0BA
# (contrasty)
color7                 #776
color15                #332

# Tabs
active_tab_foreground   #332
active_tab_background   #FFF
inactive_tab_foreground #545347
inactive_tab_background #EED

# Windows
active_border_color     #B81
inactive_border_color   #EDA
