#!/bin/sh

echo "Bases:"
for BG in 030 040 102 103 104 106 047 107; do
	echo -n "[0m${BG}: [${BG};91m "
	for FG in 90 30 92 93 94 96 37 97; do
		echo -n "[${FG}m ${FG} "
	done
	echo
done

echo "[0m"
echo "(Wrapping) colorful foregrounds:"
for BG in 030 040 102 103 104 106 047 107; do
	echo -n "[0;${BG}m"
	for FG in 032 033 091 031 035 095 034 036 032; do
		echo -n "[${FG}m ${FG} "
	done
	echo
done

echo "[0m"
echo "(Wrapping) colorful backgrounds:"
for FG in 90 30 92 93 94 96 37 97; do
	echo -n "[0;${FG}m"
	for BG in 042 043 101 041 045 105 044 046 042; do
		echo -n "[${BG}m ${BG} "
	done
	echo
done
