#!/bin/sh
#
# Copyright 1999-2002,2003 by Thomas E. Dickey
# 2020 Vit Brunner
#
# All Rights Reserved
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE ABOVE LISTED COPYRIGHT HOLDER(S) BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the
# sale, use or other dealings in this Software without prior written
# authorization.
# -----------------------------------------------------------------------------
# Show a simple 8-color test pattern

FG_CODES="39 30 31 32 33 34 35 36 37  90  91  92  93  94  95  96  97"
BG_CODES="49 40 41 42 43 44 45 46 47 100 101 102 103 104 105 106 107"

get_fg_str() {
	case $1 in
		39) echo "def ";;
		30) echo "blk ";;
		31) echo "red ";;
		32) echo "grn ";;
		33) echo "yel ";;
		34) echo "blu ";;
		35) echo "mag ";;
		36) echo "cya ";;
		37) echo "whi ";;
		90) echo "blk+";;
		91) echo "red+";;
		92) echo "grn+";;
		93) echo "yel+";;
		94) echo "blu+";;
		95) echo "mag+";;
		96) echo "cya+";;
		97) echo "whi+";;
	esac
}

get_bg_str() {
	case $1 in
		 49) echo "def ";;
		 40) echo "blk ";;
		 41) echo "red ";;
		 42) echo "grn ";;
		 43) echo "yel ";;
		 44) echo "blu ";;
		 45) echo "mag ";;
		 46) echo "cya ";;
		 47) echo "whi ";;
		100) echo "blk+ ";;
		101) echo "red+ ";;
		102) echo "grn+ ";;
		103) echo "yel+ ";;
		104) echo "blu+ ";;
		105) echo "mag+ ";;
		106) echo "cya+ ";;
		107) echo "whi+ ";;
	esac
}

CMD='echo -n'

$CMD "[0m"
$CMD "Font        Fg        "
for BG in $BG_CODES; do
	bcolor=$(get_bg_str $BG)
	$CMD "  $bcolor"
done
echo ""

for AT in 0 1 2 3; do
	case $AT in
		0) attr="norm";;
		1) attr="bold";;
		2) attr="fain";;
		3) attr="ital";;
		4) attr="undl";;
		7) attr="rvrs";;
	esac

	for FG in $FG_CODES; do
		fcolor=$(get_fg_str $FG)

		$CMD "[0;${AT}m[0;${AT}m $attr  "
		$CMD "[${FG}m[${FG}m $fcolor "

		for BG in $BG_CODES; do
			$CMD "[${BG}m [${BG}m "
		done
		echo "[0m"
	done
done
