#!/bin/sh

BASE_BGS="049 040 100 047 107"
BASE_CFS="030 090 039 037 097"

WRAP_COLOR_FGS="031 033 032 036 034 035 031"
WRAP_BRGHT_FGS="091 093 092 096 094 095 091"

WRAP_COLOR_BGS="041 043 042 046 044 045 041"
WRAP_BRGHT_BGS="101 103 102 106 104 105 101"

echo "Bases:"
for BG in $BASE_BGS; do
	echo -n "\e[0m${BG}: \e[${BG};91m "
	for FG in $BASE_CFS; do
		echo -n "\e[${FG}m ${FG} "
	done
	echo "\e[0m"
done

echo ""
echo "(Wrapping) colorful foregrounds:"
for BG in $BASE_BGS; do
	echo -n "\e[0;${BG}m"
	for FG in $WRAP_COLOR_FGS; do
		echo -n "\e[${FG}m ${FG} "
	done
	echo "\e[0m"
	for FG in $WRAP_BRGHT_FGS; do
		echo -n "\e[${FG}m ${FG} "
	done
	echo "\e[0m"
done

echo ""
echo "(Wrapping) colorful backgrounds:"
for FG in $BASE_CFS; do
	echo -n "\e[0;${FG}m"
	for BG in $WRAP_COLOR_BGS; do
		echo -n "\e[${BG}m ${BG} "
	done
	echo "\e[0m"
	for BG in $WRAP_BRGHT_BGS; do
		echo -n "\e[${BG}m ${BG} "
	done
	echo "\e[0m"
done
