#!/bin/bash

set -euo pipefail

if [ "$#" -ne 1 ]; then
	echo "Requires exactly 1 arguments, $# supplied!"
	echo
	echo "Usage: $0 <profile>"
	echo "<profile> one of: default, google, cloudflare, nextdns, hdns, hnsdns"
	exit 1
fi

CURRENT_WIFI_UUID=$(nmcli connection show --active | grep wifi | awk '{print $2}')
CURRENT_WIFI_DEVICE=$(nmcli connection show --active | grep wifi | awk '{print $4}')

DEVICES=$(echo "$CURRENT_WIFI_UUID" | wc -l)
if [ "$DEVICES" -eq 0 ]; then
	echo "No current devices found! Start with: \`nmcli connection show --active\`"
	exit 1
elif [ "$DEVICES" -gt 1 ]; then
	echo "You have multiple active wifi devices: $DEVICES. Start with \`nmcli connection show --active\`"
	exit 1
fi

IGNORE_AUTO_DNS="no"
case $1 in
	"default")
		IPV4=""
		IPV6=""
		;;

	"google")
		IPV4="4.2.2.2"
		IPV6=""
		;;

	"cloudflare")
		IPV4="1.1.1.1"
		IPV6=""
		;;

	"nextdns")
		IPV4=""
		IPV6="2a07:a8c0::9b:478b, 2a07:a8c1::9b:478b"
		IGNORE_AUTO_DNS="yes"
		;;

	"hdns")
		IPV4="103.196.38.38, 103.196.38.39"
		IPV6=""
		;;

	"hnsdns")
		IPV4="139.144.68.241, 139.144.68.242"
		IPV6="2a01:7e01:e002:c300::, 2a01:7e01:e002:c500::"
		;;

	*)
		echo "Unknown profile: $1"
		exit 1
esac


nmcli connection modify ${CURRENT_WIFI_UUID} \
	ipv4.dns "$IPV4" \
	ipv6.dns "$IPV6" \
	ipv4.ignore-auto-dns "$IGNORE_AUTO_DNS" \
	ipv6.ignore-auto-dns "$IGNORE_AUTO_DNS"
nmcli general reload dns-full
nmcli device reapply ${CURRENT_WIFI_DEVICE}
