#!/bin/sh

# lowerit
#
# convert all file names in the current directory to lower case
# only operates on plain files--does not change the name of directories
# will ask for verification before overwriting an existing file

for f in `ls`; do
	if [ ! -f $f ]; then
		# not a regular file
		continue
	fi

	# convert to lowercase and move if different
	lc=`echo $f | tr '[A-Z]' '[a-z]'`
	if [ $lc != $f ]; then
		mv -i $f $lc
	fi
done
